/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RealityEthV21WitharbitratorappealsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOSER_APPEAL_PERIOD_MULTIPLIER"
      | "LOSER_STAKE_MULTIPLIER"
      | "MULTIPLIER_DENOMINATOR"
      | "VERSION"
      | "WINNER_STAKE_MULTIPLIER"
      | "arbitrationRequests"
      | "arbitrator"
      | "arbitratorExtraData"
      | "externalIDtoLocalID"
      | "fundAppeal"
      | "getDisputeFee"
      | "getMultipliers"
      | "getTotalWithdrawableAmount"
      | "metadata"
      | "numberOfRulingOptions"
      | "realitio"
      | "reportAnswer"
      | "requestArbitration"
      | "rule"
      | "submitEvidence"
      | "withdrawFeesAndRewards"
      | "withdrawFeesAndRewardsForAllRounds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Contribution"
      | "Dispute"
      | "DisputeIDToQuestionID"
      | "Evidence"
      | "MetaEvidence"
      | "Ruling"
      | "RulingFunded"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOSER_APPEAL_PERIOD_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOSER_STAKE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MULTIPLIER_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WINNER_STAKE_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrationRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arbitratorExtraData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "externalIDtoLocalID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundAppeal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultipliers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalWithdrawableAmount",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "metadata", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numberOfRulingOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "realitio", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportAnswer",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestArbitration",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rule",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFeesAndRewards",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFeesAndRewardsForAllRounds",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LOSER_APPEAL_PERIOD_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOSER_STAKE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MULTIPLIER_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WINNER_STAKE_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitrationRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbitrator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "arbitratorExtraData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalIDtoLocalID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundAppeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalWithdrawableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfRulingOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "realitio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportAnswer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestArbitration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFeesAndRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFeesAndRewardsForAllRounds",
    data: BytesLike
  ): Result;
}

export namespace ContributionEvent {
  export type InputTuple = [
    _localDisputeID: BigNumberish,
    _round: BigNumberish,
    ruling: BigNumberish,
    _contributor: AddressLike,
    _amount: BigNumberish
  ];
  export type OutputTuple = [
    _localDisputeID: bigint,
    _round: bigint,
    ruling: bigint,
    _contributor: string,
    _amount: bigint
  ];
  export interface OutputObject {
    _localDisputeID: bigint;
    _round: bigint;
    ruling: bigint;
    _contributor: string;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeEvent {
  export type InputTuple = [
    _arbitrator: AddressLike,
    _disputeID: BigNumberish,
    _metaEvidenceID: BigNumberish,
    _evidenceGroupID: BigNumberish
  ];
  export type OutputTuple = [
    _arbitrator: string,
    _disputeID: bigint,
    _metaEvidenceID: bigint,
    _evidenceGroupID: bigint
  ];
  export interface OutputObject {
    _arbitrator: string;
    _disputeID: bigint;
    _metaEvidenceID: bigint;
    _evidenceGroupID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeIDToQuestionIDEvent {
  export type InputTuple = [_disputeID: BigNumberish, _questionID: BytesLike];
  export type OutputTuple = [_disputeID: bigint, _questionID: string];
  export interface OutputObject {
    _disputeID: bigint;
    _questionID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceEvent {
  export type InputTuple = [
    _arbitrator: AddressLike,
    _evidenceGroupID: BigNumberish,
    _party: AddressLike,
    _evidence: string
  ];
  export type OutputTuple = [
    _arbitrator: string,
    _evidenceGroupID: bigint,
    _party: string,
    _evidence: string
  ];
  export interface OutputObject {
    _arbitrator: string;
    _evidenceGroupID: bigint;
    _party: string;
    _evidence: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetaEvidenceEvent {
  export type InputTuple = [_metaEvidenceID: BigNumberish, _evidence: string];
  export type OutputTuple = [_metaEvidenceID: bigint, _evidence: string];
  export interface OutputObject {
    _metaEvidenceID: bigint;
    _evidence: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RulingEvent {
  export type InputTuple = [
    _arbitrator: AddressLike,
    _disputeID: BigNumberish,
    _ruling: BigNumberish
  ];
  export type OutputTuple = [
    _arbitrator: string,
    _disputeID: bigint,
    _ruling: bigint
  ];
  export interface OutputObject {
    _arbitrator: string;
    _disputeID: bigint;
    _ruling: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RulingFundedEvent {
  export type InputTuple = [
    _localDisputeID: BigNumberish,
    _round: BigNumberish,
    _ruling: BigNumberish
  ];
  export type OutputTuple = [
    _localDisputeID: bigint,
    _round: bigint,
    _ruling: bigint
  ];
  export interface OutputObject {
    _localDisputeID: bigint;
    _round: bigint;
    _ruling: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    _localDisputeID: BigNumberish,
    _round: BigNumberish,
    _ruling: BigNumberish,
    _contributor: AddressLike,
    _reward: BigNumberish
  ];
  export type OutputTuple = [
    _localDisputeID: bigint,
    _round: bigint,
    _ruling: bigint,
    _contributor: string,
    _reward: bigint
  ];
  export interface OutputObject {
    _localDisputeID: bigint;
    _round: bigint;
    _ruling: bigint;
    _contributor: string;
    _reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RealityEthV21Witharbitratorappeals extends BaseContract {
  connect(runner?: ContractRunner | null): RealityEthV21Witharbitratorappeals;
  waitForDeployment(): Promise<this>;

  interface: RealityEthV21WitharbitratorappealsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOSER_APPEAL_PERIOD_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  LOSER_STAKE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  MULTIPLIER_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  WINNER_STAKE_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  arbitrationRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        status: bigint;
        requester: string;
        disputeID: bigint;
        ruling: bigint;
      }
    ],
    "view"
  >;

  arbitrator: TypedContractMethod<[], [string], "view">;

  arbitratorExtraData: TypedContractMethod<[], [string], "view">;

  externalIDtoLocalID: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  fundAppeal: TypedContractMethod<
    [_questionID: BigNumberish, _ruling: BigNumberish],
    [boolean],
    "payable"
  >;

  getDisputeFee: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getMultipliers: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _WINNER_STAKE_MULTIPLIER: bigint;
        _LOSER_STAKE_MULTIPLIER: bigint;
        _LOSER_APPEAL_PERIOD_MULTIPLIER: bigint;
        _DENOMINATOR: bigint;
      }
    ],
    "view"
  >;

  getTotalWithdrawableAmount: TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _ruling: BigNumberish
    ],
    [bigint],
    "view"
  >;

  metadata: TypedContractMethod<[], [string], "view">;

  numberOfRulingOptions: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  realitio: TypedContractMethod<[], [string], "view">;

  reportAnswer: TypedContractMethod<
    [
      _questionID: BytesLike,
      _lastHistoryHash: BytesLike,
      _lastAnswerOrCommitmentID: BytesLike,
      _lastAnswerer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  requestArbitration: TypedContractMethod<
    [_questionID: BytesLike, _maxPrevious: BigNumberish],
    [bigint],
    "payable"
  >;

  rule: TypedContractMethod<
    [_disputeID: BigNumberish, _ruling: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [_questionID: BigNumberish, _evidenceURI: string],
    [void],
    "nonpayable"
  >;

  withdrawFeesAndRewards: TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _roundNumber: BigNumberish,
      _ruling: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  withdrawFeesAndRewardsForAllRounds: TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _ruling: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOSER_APPEAL_PERIOD_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOSER_STAKE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MULTIPLIER_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WINNER_STAKE_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbitrationRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        status: bigint;
        requester: string;
        disputeID: bigint;
        ruling: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "arbitrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "arbitratorExtraData"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "externalIDtoLocalID"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundAppeal"
  ): TypedContractMethod<
    [_questionID: BigNumberish, _ruling: BigNumberish],
    [boolean],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getDisputeFee"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMultipliers"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _WINNER_STAKE_MULTIPLIER: bigint;
        _LOSER_STAKE_MULTIPLIER: bigint;
        _LOSER_APPEAL_PERIOD_MULTIPLIER: bigint;
        _DENOMINATOR: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalWithdrawableAmount"
  ): TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _ruling: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "metadata"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "numberOfRulingOptions"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "realitio"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportAnswer"
  ): TypedContractMethod<
    [
      _questionID: BytesLike,
      _lastHistoryHash: BytesLike,
      _lastAnswerOrCommitmentID: BytesLike,
      _lastAnswerer: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestArbitration"
  ): TypedContractMethod<
    [_questionID: BytesLike, _maxPrevious: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "rule"
  ): TypedContractMethod<
    [_disputeID: BigNumberish, _ruling: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [_questionID: BigNumberish, _evidenceURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFeesAndRewards"
  ): TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _roundNumber: BigNumberish,
      _ruling: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFeesAndRewardsForAllRounds"
  ): TypedContractMethod<
    [
      _questionID: BigNumberish,
      _contributor: AddressLike,
      _ruling: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Contribution"
  ): TypedContractEvent<
    ContributionEvent.InputTuple,
    ContributionEvent.OutputTuple,
    ContributionEvent.OutputObject
  >;
  getEvent(
    key: "Dispute"
  ): TypedContractEvent<
    DisputeEvent.InputTuple,
    DisputeEvent.OutputTuple,
    DisputeEvent.OutputObject
  >;
  getEvent(
    key: "DisputeIDToQuestionID"
  ): TypedContractEvent<
    DisputeIDToQuestionIDEvent.InputTuple,
    DisputeIDToQuestionIDEvent.OutputTuple,
    DisputeIDToQuestionIDEvent.OutputObject
  >;
  getEvent(
    key: "Evidence"
  ): TypedContractEvent<
    EvidenceEvent.InputTuple,
    EvidenceEvent.OutputTuple,
    EvidenceEvent.OutputObject
  >;
  getEvent(
    key: "MetaEvidence"
  ): TypedContractEvent<
    MetaEvidenceEvent.InputTuple,
    MetaEvidenceEvent.OutputTuple,
    MetaEvidenceEvent.OutputObject
  >;
  getEvent(
    key: "Ruling"
  ): TypedContractEvent<
    RulingEvent.InputTuple,
    RulingEvent.OutputTuple,
    RulingEvent.OutputObject
  >;
  getEvent(
    key: "RulingFunded"
  ): TypedContractEvent<
    RulingFundedEvent.InputTuple,
    RulingFundedEvent.OutputTuple,
    RulingFundedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "Contribution(uint256,uint256,uint256,address,uint256)": TypedContractEvent<
      ContributionEvent.InputTuple,
      ContributionEvent.OutputTuple,
      ContributionEvent.OutputObject
    >;
    Contribution: TypedContractEvent<
      ContributionEvent.InputTuple,
      ContributionEvent.OutputTuple,
      ContributionEvent.OutputObject
    >;

    "Dispute(address,uint256,uint256,uint256)": TypedContractEvent<
      DisputeEvent.InputTuple,
      DisputeEvent.OutputTuple,
      DisputeEvent.OutputObject
    >;
    Dispute: TypedContractEvent<
      DisputeEvent.InputTuple,
      DisputeEvent.OutputTuple,
      DisputeEvent.OutputObject
    >;

    "DisputeIDToQuestionID(uint256,bytes32)": TypedContractEvent<
      DisputeIDToQuestionIDEvent.InputTuple,
      DisputeIDToQuestionIDEvent.OutputTuple,
      DisputeIDToQuestionIDEvent.OutputObject
    >;
    DisputeIDToQuestionID: TypedContractEvent<
      DisputeIDToQuestionIDEvent.InputTuple,
      DisputeIDToQuestionIDEvent.OutputTuple,
      DisputeIDToQuestionIDEvent.OutputObject
    >;

    "Evidence(address,uint256,address,string)": TypedContractEvent<
      EvidenceEvent.InputTuple,
      EvidenceEvent.OutputTuple,
      EvidenceEvent.OutputObject
    >;
    Evidence: TypedContractEvent<
      EvidenceEvent.InputTuple,
      EvidenceEvent.OutputTuple,
      EvidenceEvent.OutputObject
    >;

    "MetaEvidence(uint256,string)": TypedContractEvent<
      MetaEvidenceEvent.InputTuple,
      MetaEvidenceEvent.OutputTuple,
      MetaEvidenceEvent.OutputObject
    >;
    MetaEvidence: TypedContractEvent<
      MetaEvidenceEvent.InputTuple,
      MetaEvidenceEvent.OutputTuple,
      MetaEvidenceEvent.OutputObject
    >;

    "Ruling(address,uint256,uint256)": TypedContractEvent<
      RulingEvent.InputTuple,
      RulingEvent.OutputTuple,
      RulingEvent.OutputObject
    >;
    Ruling: TypedContractEvent<
      RulingEvent.InputTuple,
      RulingEvent.OutputTuple,
      RulingEvent.OutputObject
    >;

    "RulingFunded(uint256,uint256,uint256)": TypedContractEvent<
      RulingFundedEvent.InputTuple,
      RulingFundedEvent.OutputTuple,
      RulingFundedEvent.OutputObject
    >;
    RulingFunded: TypedContractEvent<
      RulingFundedEvent.InputTuple,
      RulingFundedEvent.OutputTuple,
      RulingFundedEvent.OutputObject
    >;

    "Withdrawal(uint256,uint256,uint256,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
